language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: MOyZxVs7P+IIJu0tRFFMK/hWYg17GGiHI+MJ0HK06AdW9J1YtwzRNTNVI6Kmb9Ho1gRaGhXSllQEf66/8juyL98Z/fsGSeB1VzK0a3t9trLQdK3ju1KgwPLKKPxOm3fjwpDz+WOqotNtsYW8jTudI1ULdRB50MMmopHoMrsNOF+iL3ARBaAg6deew50xgOEAFuFa54P7wL2BAc4+8Dss6SysIcExK4mBEQvx6ZNFKFKJXXbrDivCpcMvKwxoaJxGy54p3tBaG4lrgxBcKa0ei0rjuDECzIQ8mpXzZkIr0nzLJJfa4WH54crkclOY3UXEXvzIPUVGbYgrKn5cxAtDKHmkCjHYnM2Sj3FGwHAtTh75fzZBAZxeLZRL7i+VuiSYY/NWOAJF2aH0YmEDWBa9+BSuA+IFyH7qr/DlcxruMQNCwILAJNCHzDILXzpGnWpGgY+52lTob6luQTTswZWccDr3v/nmwHTVoda63kVi6aFHJxniKW+yg8CoyJXf4fB0yi8/gWGRzNStFgMGnal3Qo3QmK/pbe+EqfO2js764JVOoYr3uM0dqzHaYVPWehLLwIPCea9ifsAosbfAY2gFwt6uQn6f01rqt5DehnRQs9N416+h1xWKp/6RO9oe4UdpMGUQIG4KLTgEF69aMv77IioOVr4KDqIWC/1MxaNfh9E=
  app: serene-dawn-19882
  on:
    repo: catperez81/node-shopping-list-integration-tests-master
